version: "3.9"


services:
  django:
    build: .
    command: python /app/backend/manage.py runserver 0.0.0.0:8000
    container_name: django
    image: django:app
    depends_on:
      - migrations
      - postgres
    ports:
      - 8000:8000 
    volumes:
      - .:/app/backend
  migrations:
    image: django
    command: python manage.py migrate
    volumes:
      - .:/app/backend
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - ./app/.env
    expose:
      - 5432
    environment:
      - POSTGRES_DB=DB_NAME
      - POSTGRES_USER=DB_USER
      - POSTGRES_PASSWORD=DB_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
  redis:
    container_name: redis
    image: redis:7
    restart: always
    expose:
      - 6379
    volumes:
      - cache:/data
   
volumes:
  postgres_data: null
  cache: null
